### ISSUE TITLE
NPM package doesn't include type definitions

### ISSUE THREAD

**Issue by spiffytech** [forgojs/forgo-state#1]
The published `forgo-state@0.0.3` package on NPM (published 8 minutes ago, I installed it 7 minutes ago, lucky me) doesn't have a `.d.ts` file. As a workaround, I can get typings by importing `from "forgo-state/src/index"`.

**Comment by jeswin** [comment]
Wow, there seems to be a problem with my build. Let me fix that right away. Thanks.

**Comment by jeswin** [comment]
Ah, forgot to add an .npmignore. When npm doesn't find it, it'll default to using .gitignore; which ignores the dist/ directory.

Published forgo-state@0.0.5. You could close the issue after verifying.

**Comment by spiffytech** [comment]
Verified, thanks!
